### ISSUE TITLE
Repeated crashes of the language server

### ISSUE THREAD

**Issue by BladeMF** [recca0120/vscode-phpunit#122]
When changing the tests I have this very frequent error:
```js
n [Error]: Unhandled method TestLoadStartedEvent-f0d8adf93a6b1b96be7c532ee0c349bf
    at /root/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /root/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/root/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Error - 6:27:55 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by arminetsw** [comment]
Same problem here

**Comment by recca0120** [comment]
version 3.0, lsp is removed
