### ISSUE TITLE
The PHPUnit Language Server server crashed on Linux environment

### ISSUE THREAD

**Issue by jonz94** [recca0120/vscode-phpunit#15]
先感謝 @recca0120 大大寫了這麼好用的套件XDD

我遇到的問題是在安裝套件之後 vscode 會出現以下錯誤訊息

* Error message from vscode
```
The PHPUnit Language Server server crashed 5 times in the last 3 minutes.
The server will not be restarted.
```

* Error log from PHPUnit Language Server output
```
Error: Cannot find module './snippets'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/jonz94/.vscode/extensions/recca0120.vscode-phpunit-2.0.30/server/out/server.js:12:20)
    at Object.<anonymous> (/home/jonz94/.vscode/extensions/recca0120.vscode-phpunit-2.0.30/server/out/server.js:213:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
[Info  - 1:38:52 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:604
    throw err;
    ^
```

發現到是 `~/.vscode/extensions/recca0120.vscode-phpunit-2.0.30/server/out/server.js` 這個檔案裡面的這行出現問題
```javascript
const snippets_1 = require("./snippets");
```
因為預期要 require 的 `Snippets.js` 檔名是大寫開頭的，跑到這行時就炸掉了XDD

PS. 我有在 Windows 和 macOS 的 vscode 也安裝這個套件，都可以正常運作，而且 `server.js` 的那行一樣是 `require("./snippets")`，不過在 Windows 和 macOS 上這行好像不會出問題XDD

目前自己暫時的解決方法是手動去修改 `server.js` 這個檔案
```diff
-const snippets_1 = require("./snippets");
+const snippets_1 = require("./Snippets");
```

不過感覺這不是正規的解法XD，畢竟這個檔案是被 compile 出來的檔案

**Comment by recca0120** [comment]
這我有發現
晚點再放出新版

**Comment by recca0120** [comment]
剛釋出一個版本，這問題應該被修復了才對

**Comment by jonz94** [comment]
目前升級套件到最新版本之後就直接可以使用了，感謝！
