### ISSUE TITLE
Unable to reload tests : UnhandledPromiseRejectionWarning: Error: Unhandled method TestLoadStartedEven

### ISSUE THREAD

**Issue by gnicol-bzh** [recca0120/vscode-phpunit#33]
Hello,

The list of the tests is correctly updated when reloading VS Code. All the tests run without any error.

But when I click on "reload tests" button (or using the related command), I have an error in the output console.

Has anyone come across this problem before ?

Thank you!

_NB: I'm not allowed (yet) to upgrade PHP version, for dev servers are still under PHP 7.0.x._

_console error at the end of first test run (not always the first, but very often)_
```node
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at lazyFs.read (internal/fs/streams.js:165:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
[Info  - 17:16:32] Connection to server got closed. Server will restart.
```

_then, console error when cliking on reload button or any run button_
```node
(node:11312) UnhandledPromiseRejectionWarning: Error: Unhandled method TestLoadStartedEvent-3921af80150269569a39383d0af40851
    at c:\Users\Greg\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:1:9288
    at c:\Users\Greg\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:1:9582
    at Immediate.G.C.size.setImmediate (c:\Users\Greg\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:1:9943)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

_settings.json_
```json
{
...
  "phpunit.args": [
    "--configuration",
    "C:/myproject/phpunit-fast.xml",
  ],
  "phpunit.files": "{front,backend}/unit_tests/**/*Test.php",
...
}
```

_composer.json_
```json
{
...
	"require-dev" : {
		"mockery/mockery" : "0.9.9",
		"phpunit/php-code-coverage" : "^5.3",
		"phpunit/php-file-iterator" : "1.4.5",
		"phpunit/php-text-template" : "1.2.1",
		"phpunit/php-timer" : "^1.0.9",
		"phpunit/php-token-stream" : "^2.0.1",
		"phpunit/phpunit" : "^6.5.13",
		"phpunit/phpunit-mock-objects" : "^5.0.9",
		"sebastian/environment": "^3.0",
		"sebastian/version": "^2.0.1",
		"sebastian/comparator": "^2.0.2",
		"sebastian/diff": "^2.0",
		"sebastian/exporter": "^3.1",
		"sebastian/global-state": "^2.0",
		"sebastian/recursion-context": "^3.0"
	},
...
}
```

_node -v_
```
v10.16.0
```

_php -v in terminal_
```
PHP 7.0.33 (cli) (built: Dec  5 2018 21:22:29) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

_wamp_
```
WampServer Version 3.1.9 64bit
Created by Romain Bourdon (2005)
Maintainer / Upgrade to 2.5 by Herve Leclerc
Upgrade to 3 by Otomatic (wampserver@otomatic.net)
Multi styles for homepage by Jojaba
Installer by Inno Setup: http://www.jrsoftware.org/isinfo.php
Forum Wampserver: http://forum.wampserver.com/index.php
______________________ Versions used ______________________
Apache 2.4.39 Port 80- PHP 7.0.33
PHP 5.6.31 for CLI (Command-Line Interface)

```

![image](https://user-images.githubusercontent.com/11173645/61859908-589f3880-aec9-11e9-94bd-19af565a8792.png)

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by Xachman** [comment]
@recca0120 is there a version where this does not happen?

**Comment by recca0120** [comment]
try version 3.0
